<template>
  <div class="component">


  </div>
</template>


<script>
import { defineComponent } from 'vue'
  import { NButton , NCard, NCarousel ,N} from 'naive-ui'

  export default defineComponent({
    components: {
      NButton, NCard, NCarousel
    }
  })
</script>


<style lang="scss" scoped>

</style>

 import { defineComponent } from 'vue'
  import { NButton , NCard, NCarousel ,N} from 'naive-ui'

  export default defineComponent({
    components: {
      NButton, NCard, NCarousel
    }
  })
  // note to use this in a template you just need to
  // npm i -D naive-ui  
  // they look like <n-button></n-button>
//to use the ones you want go into import and 
//type N and you will see a list of option
